### ISSUE TITLE
Trabalho 1

### ISSUE THREAD

**Issue by FranciscoLDB** [FranciscoLDB/Redes-de-Computadores#1]
# To-Do List: Implementação de Aplicação UDP

## Procurar Código de Exemplo
- [x] Encontrar um código "Hello World" usando servidor UDP e cliente.

## Configuração do Servidor UDP
- [x] Escolher uma porta para comunicação (maior que 1024).
- [x] Implementar a recepção de dados no servidor.
- [x] Tratar os dados recebidos (propor um protocolo próprio, ex.: GET /arquivo).
- [x] Implementar a transmissão do arquivo requisitado pelo cliente (arquivo > 1 MB).
- [x] Dividir o arquivo em pedaços (considerar tamanho do buffer e MTU).
- [x] Definir e implementar o tamanho do buffer.
- [x] Implementar checksums para verificação de integridade.
- [x] Numerar os pedaços do arquivo.
- [x] Implementar resposta para arquivo não encontrado.

## Configuração do Cliente UDP
- [x] Configurar o endereço da máquina e porta do servidor.
- [x] Implementar a requisição de um arquivo.
- [x] Dar opção ao usuário para descartar parte do arquivo (simular perda de dados).
- [x] Receber, montar e conferir o arquivo recebido (checksums).
- [x] Apresentar o arquivo requisitado se estiver OK.
- [x] Verificar e solicitar reenvio de pedaços faltantes se o arquivo não estiver OK.
- [x] Interpretar e tratar erros (ex.: arquivo não encontrado).
- [x] Implementar limite de tempo de resposta.

## Testes e Validações
- [x] Testar o que acontece se o servidor for desligado durante a transmissão e religado depois.
- [x] Testar com dois clientes simultâneos requisitando arquivos diferentes.

## Defesa do Trabalho
- [x] Preparar a defesa do trabalho para o professor nas aulas definidas.

## Considerações Importantes
- [x] Usar Socket UDP diretamente, sem bibliotecas que mascarem o trabalho.
- [x] Implementar somas de verificação (checksums) ou resumos criptográficos (MD5, SHA) para verificação de integridade.
